### ISSUE TITLE
Support Combine in Linux through OpenCombine

### ISSUE THREAD

**Issue by muizidn** [gringoireDM/EnumKit#3]
Make Combine extension available in Linux (or lower Mac) would be a great support for developers

**Comment by gringoireDM** [comment]
I don't think it would be wise to enforce a dependency to who might not want to adopt it.

The combine extension exists only because it does not require any third party dependency to be enforced. I might build an OpenCombine EnumKit extension that will be separate, like I did for [RxEnumKit](https://github.com/gringoireDM/RxEnumKit)

**Comment by muizidn** [comment]
Ah, yes. Of course. I want to contribute ☺️

**Comment by gringoireDM** [comment]
Thank you for your support. If you want, feel free to start by creating a porting of the existing Combine extensions. At the moment I don't have buffer to do it myself. I'll contribute to the new Repo as soon as I'll free myself from some of my current duties. :)
